Querying DAS for files...
the query is file run=344518 dataset=/ExpressCosmics/Commissioning2021-Express-v1/FEVT lumi=1
Sleeping, then retrying DAS
Sleeping, then retrying DAS
DAS failed 3 times- I give up
found files:  []
Traceback (most recent call last):
  File "/afs/cern.ch/user/s/seyang/private/GEM-Workspace/SW-Dev/220112_GEM-Efficiency-By-GEMCSCSegment/test/unittest/./CMSSW_12_3_X_2022-03-08-1100/src/DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py", line 15, in <module>
    process.load("DQM.Integration.config.unittestinputsource_cfi")
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-08-1100/python/FWCore/ParameterSet/Config.py", line 722, in load
    module = __import__(moduleName)
  File "/afs/cern.ch/user/s/seyang/private/GEM-Workspace/SW-Dev/220112_GEM-Efficiency-By-GEMCSCSegment/test/unittest/CMSSW_12_3_X_2022-03-08-1100/python/DQM/Integration/config/unittestinputsource_cfi.py", line 99, in <module>
    command = "edmFileUtil --catalog file:/cvmfs/cms-ib.cern.ch/SITECONF/local/PhEDEx/storage.xml?protocol=xrootd --events %s | tail -n +9 | head -n -5 | awk '{ print $3 }'" % read[0]
IndexError: list index out of range
